name: Python Tests

on:
  pull_request:
    branches: [ main ]  # or 'master' depending on your default branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # you can specify a specific version like '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install .

    - name: Run tests
      run: |
        pytest pelican/plugins/tests
